# Generated by Django 2.1.2 on 2018-10-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0003_auto_20181023_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
