# Generated by Django 2.1.2 on 2018-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0007_post_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to='posts'),
        ),
    ]
