# Generated by Django 2.1.2 on 2018-10-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0008_auto_20181008_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
    ]
