# Generated by Django 2.1.2 on 2018-10-08 18:28

from django.db import migrations, models
import photo_blog.models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0011_auto_20181008_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=photo_blog.models.get_image_path),
        ),
    ]
