# Generated by Django 2.1.2 on 2018-10-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0015_auto_20181011_0805'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='content',
            new_name='message',
        ),
    ]
