# Generated by Django 2.1.2 on 2018-10-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0016_auto_20181011_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='content',
        ),
    ]
