# Generated by Django 2.1.2 on 2018-10-11 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0017_auto_20181011_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
