# Generated by Django 2.1.2 on 2018-10-16 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_blog', '0021_auto_20181016_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
    ]
