# Generated by Django 2.1.2 on 2018-10-16 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photo_blog', '0022_remove_notification_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date_posted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
