# Generated by Django 2.1.2 on 2018-10-17 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_followers'),
        ('photo_blog', '0023_auto_20181016_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='followed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='liked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
